# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_auto_20170330_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='duration',
            new_name='durationn',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
