# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_auto_20170331_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='durationn',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
