# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0006_auto_20170331_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
